language: julia
os:
  - linux
  # - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("WriteVTK"); Pkg.test("WriteVTK"; coverage=true)'
